config/routes.rb
Rails.application.routes.draw do
  root "qr_codes#index"
  resources :qr_codes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/qr_code.rb
class QrCode < ApplicationRecord
  require "mini_magick"

  has_one_attached :original_image
  has_one_attached :logo
  has_one_attached :combined_image

  def generate_qr_code!
    qr = RQRCode::QRCode.new(url)
    original_qr = qr.as_png(size: 400,
      bit_depth: 1,
      border_modules: 4,
      color_mode: ChunkyPNG::COLOR_GRAYSCALE,
      color: "black",
      file: nil,
      fill: "white")
    original_image.attach(io: StringIO.new(original_qr.to_s), filename: "original_qr.png", content_type: "image/png")
    save!
  end

  def generate_combined_image!
    logo_image = MiniMagick::Image.open(logo)
    qr_code_image = MiniMagick::Image.open(original_image)

    updated_logo_image = ImageProcessing::MiniMagick.source(logo_image).resize_and_pad(100, 100, background: "white").call

    composite_qr_code = qr_code_image.composite(updated_logo_image) do |c|
      c.compose "Over"
      c.gravity "center"
      c.colorspace "sRGB"
    end

    combined_image.attach(filename: "combined_qr_code.png",
                          io: File.open(composite_qr_code.path),
                          content_type: "image/png")
    save!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/qr_codes_controller.rb
class QrCodesController < ApplicationController
  before_action :set_qr_code, only: %i[ show edit update destroy ]

  # GET /qr_codes or /qr_codes.json
  def index
    @qr_codes = QrCode.all
  end

  # GET /qr_codes/1 or /qr_codes/1.json
  def show
  end

  # GET /qr_codes/new
  def new
    @qr_code = QrCode.new
  end

  # GET /qr_codes/1/edit
  def edit
  end

  # POST /qr_codes or /qr_codes.json
  def create
    @qr_code = QrCode.new(qr_code_params)

    respond_to do |format|
      if @qr_code.save
        @qr_code.generate_qr_code!
        @qr_code.generate_combined_image!
        format.html { redirect_to qr_code_url(@qr_code), notice: "Qr code was successfully created." }
        format.json { render :show, status: :created, location: @qr_code }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @qr_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qr_codes/1 or /qr_codes/1.json
  def update
    respond_to do |format|
      if @qr_code.update(qr_code_params)
        @qr_code.generate_qr_code!
        @qr_code.generate_combined_image!
        format.html { redirect_to qr_code_url(@qr_code), notice: "Qr code was successfully updated." }
        format.json { render :show, status: :ok, location: @qr_code }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @qr_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qr_codes/1 or /qr_codes/1.json
  def destroy
    @qr_code.destroy!

    respond_to do |format|
      format.html { redirect_to qr_codes_url, notice: "Qr code was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qr_code
      @qr_code = QrCode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def qr_code_params
      params.require(:qr_code).permit(:url, :logo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qr_codes_helper.rb
module QrCodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QrCodeGenerator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/qr_codes/_form.html.erb
<%= form_with(model: qr_code, class: "contents") do |form| %>
  <% if qr_code.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(qr_code.errors.count, "error") %> prohibited this qr_code from being saved:</h2>

      <ul>
        <% qr_code.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :logo %>
    <%= form.file_field :logo %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/qr_codes/_qr_code.html.erb
<div id="<%= dom_id qr_code %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Url:</strong>
    <%= qr_code.url %>
    <%= image_tag qr_code.logo %>
    <%= image_tag qr_code.original_image if qr_code.original_image.attached? %>
    <%= image_tag qr_code.combined_image if qr_code.combined_image.attached? %>
  </p>

</div>

app/views/qr_codes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing qr code</h1>

  <%= render "form", qr_code: @qr_code %>

  <%= link_to "Show this qr code", @qr_code, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to qr codes", qr_codes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/qr_codes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Qr codes" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Qr codes</h1>
    <%= link_to "New qr code", new_qr_code_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="qr_codes" class="min-w-full">
    <% @qr_codes.each do |qr_code| %>
      <%= render qr_code %>
      <p>
        <%= link_to "Show this qr code", qr_code, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/qr_codes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New qr code</h1>

  <%= render "form", qr_code: @qr_code %>

  <%= link_to "Back to qr codes", qr_codes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/qr_codes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @qr_code %>

    <%= link_to "Edit this qr code", edit_qr_code_path(@qr_code), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to qr codes", qr_codes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this qr code", @qr_code, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>